### ISSUE TITLE
Landscape/Portrait modes, lock and config

### ISSUE THREAD

**Issue by tintin42** [sluedecke/tonality#1]
Since tonality works well in either portrait or landscape it would be great to improve this functionality slightly. 
  1. One easy fix would be to have a switch to lock into either mode so the layout does not flip around. It would be good to be able to switch to landscape when you have locked the screen orintation in the OS.
  2. Another useful thing would be to keep separate keyboard layout configurations for these two modes. As it is now, if you have configured for landscape and turn to portrait, the spacing of the keys would most likely be too narrow and tall to be useful. The same thing applied the other way around of course, so it would be great if these two configurations were separate.

**Comment by sluedecke** [comment]
Good points, the screen orientation really need separate configurations.  Once I figured out how to best integrate it, I can do it.

**Comment by sluedecke** [comment]
Some notes:

* currently the dimensions of the keys are handled by semitone components
* tonality needs to store a set of values per orientation, overriding the semitone code
* tonality needs to ensure that it receives orientation change events (should happen automatically)
