### ISSUE TITLE
not an issue, just a compliment

### ISSUE THREAD

**Issue by ghost** [sluedecke/tonality#17]
thanks for this, very cool piano, as far as I know it's the only one on f-droid with the exception of a 9 years old barebones program

**Comment by sluedecke** [comment]
Thank you very much!  Tonality was not possible without prior work, namely

Semitone - tuner, metronome, and piano for Android
by Andy Tockman <[andy@tck.mn](mailto:andy@tck.mn)>
Official website: https://tck.mn/semitone/
