### ISSUE TITLE
F-droid verion: Key switcher not working

### ISSUE THREAD

**Issue by jakejgw** [sluedecke/tonality#3]
The current F-Droid verision (1.2) does not respond when the "C" (key switcher) button is pressed. Play Store version (also 1.2) does work. Different compile options? The buttons on the bottom also display in a different order.

**Comment by sluedecke** [comment]
will be one behavior again with 1.3, thanks for pointing it out.

In fact the both 1.2 versions differ in the aspects you mentioned (`git diff playstore/1.2 version/1.2`)
