### ISSUE TITLE
Custom colorization of scales

### ISSUE THREAD

**Issue by strk** [sluedecke/tonality#8]
I love this app, thanks a lot for making it available!

For better usability, I think it would be useful to change the colors of scale. There are too many colors (white and black for non-selected, yellow/brown for selected...).

My preference would be to have something like grayed-out non-selected keys and highlighted selected keys (even same color would be ok, don't need to have black/white I'd think).

Given my preferences are subjective, having customizability could help

**Comment by sluedecke** [comment]
Interessting idea, can you create a simple example of how it might look like?

Implementation wise it could be a selectable theme. Predefined themes are quite easy to implement, the biggest part is the customization screen.

**Comment by strk** [comment]
The idea could be to make all non-selected keys white, and selected
keys yello. What I find hard to understand is that there are basically
4 colors when you pick (for example) a natural minor C:

  - Yellow: D F G
  - Brown: C Eb Ab Bb
  - Black: Db Gb
  - White: E A B

I think it would be better to have only 2 colors, so even sharps/flats
would be yellow if selected or white if unselected.
It'd be ok to use brown for the tonic.

I'd pick such color scheme w/out bothering with customization, as I
do understand customization makes the task harder :)

**Comment by sluedecke** [comment]
So it would use three colors:

brown for the root note (=tonic)
yellow for members of the scale
white for all other keys

I'll give it a try.

**Comment by sluedecke** [comment]
With frames and implementation it looks like seen below.

![Untitled](https://user-images.githubusercontent.com/7710530/64688886-9bbf6600-d48d-11e9-86ad-3c5fa3b43362.png)

**Comment by strk** [comment]
Uhm, it's still confusing.

How about just overlaying a little colored circle above the key ?
Just like the labeling. Maybe only labeling the keys which belong
to the scale
